server:
  port: 8082

spring:
  application:
    name: auth-service
  security:
    jwt:
      exp:
        time: 86400000
      secret:
        key: a0fcbd306a451411520fb5e92f976a38fb5f587cde0b2b7894b9e120c84059baaad36ec8ec3d2bd5efc0aa021735ca631e04efdf0235b1b2a99ecfc44e87608f

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      partnerService:
        failureRateThreshold:
        waitDurationInOpenState:
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize:
  timelimiter:
    instances:
      partnerService:
        timeoutDuration: 3s